## Understanding multi-dimensional arrays and their operations in NumPy

### Exercise 1: Create an Array

You are working on an image processing project and need to create a NumPy array to represent an image. Create a 2-dimensional array with dimensions (32, 32) and initialize it with random values between 0 and 255.

In [1]:
import numpy as np

# TODO: Create a 2-dimensional array with dimensions (32, 32) and initialize it with random values between 0 and 255
array_2d = np.random.randint(0, 256, size=(32, 32))

print(array_2d)

[[ 91  47 148 ... 214 185 182]
 [219 113 192 ... 250 228  93]
 [ 33 229  81 ...  34 108  27]
 ...
 [  9 224   1 ... 103  60 121]
 [155 152  49 ...  91 109 145]
 [ 10 215   8 ...  21  35  64]]


### Exercise 2: Element-wise Operations

You are implementing a machine learning algorithm and need to perform element-wise operations on arrays. Given two arrays of the same shape, calculate the element-wise sum, difference, and product.

In [2]:
# TODO: Define two arrays A and B of the same shape
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# TODO: Calculate the matrix element-wise sum
sum_matrix = A + B

# TODO: Calculate the matrix element-wise difference
diff_matrix = A - B

# TODO: Calculate the matrix element-wise product
prod_matrix = A * B

print("Sum:")
print(sum_matrix)
print("Difference:")
print(diff_matrix)
print("Product:")
print(prod_matrix)

Sum:
[[ 6  8]
 [10 12]]
Difference:
[[-4 -4]
 [-4 -4]]
Product:
[[ 5 12]
 [21 32]]


### Exercise 3: Array Slicing

You have a dataset of images stored as a 3-dimensional array of shape (100, 64, 64). Extract a subset of images from the dataset by slicing along the first axis to create a new array of shape (10, 64, 64).

In [3]:
# Generate random images
image_width = 64
image_height = 64
num_images = 100
random_images = np.random.randint(0, 256, size=(num_images, image_height, image_width), dtype=np.uint8)

# TODO: Extract a subset of images from the dataset by slicing along the first axis to create a new array of shape (10, 64, 64)
subset_images = random_images[:10]

# Print the shape of the subset images
print("Shape of subset images:", subset_images.shape)

Shape of subset images: (10, 64, 64)


## Performing basic mathematical and statistical operations using NumPy

### Exercise 4: Array Statistics

You are analyzing data from a survey and need to compute basic statistical measures. Given an array of survey responses, calculate the mean, median, and standard deviation.

In [4]:
# TODO: Define an array of survey responses
survey_responses = np.array([3, 4, 5, 4, 2, 1, 5, 3, 4, 5])

# TODO: Calculate the mean, median, and standard deviation
mean = np.mean(survey_responses)
median = np.median(survey_responses)
std_dev = np.std(survey_responses)

# Print the mean, median, and standard deviation
print("Mean:", mean)
print("Median:", median)
print("Standard Deviation:", std_dev)

Mean: 3.6
Median: 4.0
Standard Deviation: 1.2806248474865698


### Exercise 5: Matrix Operations

You are working on a linear regression problem and need to perform matrix operations. Given two matrices A and B of appropriate dimensions, calculate the matrix product, matrix transpose, and matrix determinant.

In [5]:
import numpy as np

# TODO: Define the matrices A and B
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])

# TODO: Calculate the matrix product
product = np.dot(A, B) # or use @ operator

# TODO: Calculate the matrix transpose
transpose = A.T

# TODO: Calculate the matrix determinant
determinant = np.linalg.det(A)

# Print the results
print("Matrix Product:\n", product)
print("Matrix Transpose:\n", transpose)
print("Matrix Determinant:", determinant)

Matrix Product:
 [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]
Matrix Transpose:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]
Matrix Determinant: -9.51619735392994e-16


### Exercise 6: Random Sampling

You are simulating a data collection process and need to generate random samples. Create a random sample of size 50 from a given array using NumPy's random sampling functions.

In [6]:
# Defining an array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# TODO: Create a random sample of size 50 from a given array using NumPy's random sampling functions
random_sample = np.random.choice(arr, size=50)

# Print the random sample
print("Random Sample:", random_sample)

Random Sample: [ 2  6  3  2  7  2  2  4  9  3  3  4  7  2  4  6  4  7  3  5  9  9  9  6
  3  8  7  7  1  3  1 10 10  7  5  7  4  5  7  7  4  9  6  7  4  2  4  4
  3  7]


## Exploring advanced operations with NumPy arrays

### Exercise 7: Array Broadcasting

You are working on a neural network project and need to perform element-wise operations between arrays of different shapes. Use array broadcasting to add a 1-dimensional array of shape (3,) to a 2-dimensional array of shape (2, 3).

In [7]:
# TODO: Define the 1-dimensional array
arr1 = np.array([1, 2, 3])

# TODO: Define the 2-dimensional array
arr2 = np.array([[4, 5, 6], [7, 8, 9]])

# TODO: Use array broadcasting to add the 1-dimensional array to the 2-dimensional array
result = arr1 + arr2

# Print the result
print("Result:\n", result)

Result:
 [[ 5  7  9]
 [ 8 10 12]]


### Exercise 8: Universal Functions (ufuncs)

You are working on a signal processing task and need to apply a mathematical function element-wise to an array. Apply the exponential function to each element of a given array.

In [8]:
# TODO: Define the array
arr = np.array([0, np.pi/4, np.pi/2, 3*np.pi/4, np.pi])

# TODO: Apply the cosine function to each element of the array
result = np.cos(arr)

# Print the result
print("Result:", result)

Result: [ 1.00000000e+00  7.07106781e-01  6.12323400e-17 -7.07106781e-01
 -1.00000000e+00]


### Exercise 9: Indexing and Masking

You have a dataset of student scores stored as a 2-dimensional array. Identify and extract the scores of students who scored above a certain threshold.

In [9]:
# TODO: Define the threshold
threshold = 80

# TODO: Generate an example 2-dimensional array of student scores
scores = np.array([[75, 82, 90],
                   [88, 65, 72],
                   [92, 78, 85]])

# TODO: Use boolean indexing to extract scores above the threshold
above_threshold = scores[scores > threshold]

# Print the scores above the threshold
print("Scores above the threshold:", above_threshold)

Scores above the threshold: [82 90 88 92 85]


## Broadcasting and vectorized operations

### Exercise 10: Array Reshaping

You have a 1-dimensional array of size 12 and need to reshape it into a 2-dimensional array of shape (3, 4). Reshape the array accordingly.

In [10]:
# TODO: Reshape the 1-dimensional array into a 2-dimensional array of shape (3, 4)
array_1d = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
array_2d = array_1d.reshape((3, 4))

# Print the reshaped array
print("Reshaped array:")
print(array_2d)

Reshaped array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


### Exercise 11: Vectorized Functions

You are working on an image processing task and need to apply a vectorized function to each pixel of an image. Apply a vectorized grayscale conversion function to a given RGB image.

In [11]:
import numpy as np

# TODO: Define the RGB image (example dimensions: height=32, width=32, channels=3)
image = np.random.randint(0, 256, size=(32, 32, 3), dtype=np.uint8)

# Define the relative luminance weights for the RGB channels, respectively, in the grayscale conversion formula
grayscale_filter = np.array([0.2989, 0.5870, 0.1140])

# TODO: Apply vectorized grayscale conversion using the np.dot() function with the image[..., :3] and grayscale_filter
grayscale_image = np.dot(image[..., :3], grayscale_filter)

# Print the grayscale image
print("Grayscale image:")
print(grayscale_image)

Grayscale image:
[[201.9481 145.5224 156.9765 ...  76.5214  76.6208  44.1357]
 [ 59.1968  36.6311  85.9633 ... 172.3922  36.4789 156.6165]
 [ 52.4058  97.894  141.3725 ... 112.4501  99.6884 188.5847]
 ...
 [222.0502  83.9309  18.194  ... 105.4558 177.9141 152.9141]
 [127.2286 134.1173 130.1673 ...  55.7529  86.0802 131.1872]
 [ 68.8283 175.2872  56.6774 ... 122.5711 114.0728 170.1206]]


### Exercise 12: Vectorized Arithmetic Operations

You have two arrays representing sensor measurements and need to perform element-wise arithmetic operations. Perform addition, subtraction, multiplication, and division between the two arrays.

In [12]:
import numpy as np

# TODO: Define two arrays, A and B, representing sensor measurements
A = np.array([1, 2, 3, 4])
B = np.array([5, 6, 7, 8])

# TODO: Compute element-wise addition
addition = A + B

# TODO: Compute element-wise subtraction
subtraction = A - B

# TODO: Compute element-wise multiplication
multiplication = A * B

# TODO: Compute element-wise division
division = A / B

# TODO: Print the results
print("Addition:", addition)
print("Subtraction:", subtraction)
print("Multiplication:", multiplication)
print("Division:", division)

Addition: [ 6  8 10 12]
Subtraction: [-4 -4 -4 -4]
Multiplication: [ 5 12 21 32]
Division: [0.2        0.33333333 0.42857143 0.5       ]


## Array manipulation techniques

### Exercise 13: Array Concatenation

You have two arrays and need to concatenate them along a specified axis. Concatenate a 1-dimensional array of shape (4,) and a 2-dimensional array of shape (2, 4) along the row axis.

In [13]:
import numpy as np

# TODO: Define a 1-dimensional (4,) array and a 2-dimensional array (2, 4)
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([[5, 6, 7, 8], [9, 10, 11, 12]])

# TODO: Concatenate along the column axis (axis=0)
concatenated = np.vstack((arr1, arr2))

# TODO: Print the result
print("Concatenated array:")
print(concatenated)

# The new dimensions are (3, 4)

# TODO: Try to concatenate along the row axis (axis=0)
# This will raise a ValueError because the shapes of the arrays don't match along the concatenation/stacking axis.

Concatenated array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


### Exercise 14: Array Splitting

You have an array and need to split it into multiple smaller arrays of equal size. Split a given 1-dimensional array of size 10 into two arrays of size 5.

In [14]:
import numpy as np

# TODO: Define a 1-dimensional array of size 10
arr = np.arange(10)

# TODO: Split the array into two arrays of size 5
split_arrays = np.split(arr, 2)

# TODO: Print the split arrays
print("Split arrays:", split_arrays)

Split arrays: [array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]


### Exercise 15: Array Transposition

You have a 2-dimensional array and need to transpose it, swapping the rows and columns. Transpose a given 2-dimensional array of shape (3, 4).

In [15]:
# TODO: Define a 2-dimensional array of shape (3, 4)
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

# TODO: Transpose the array using .T method
transposed_T = arr.T

# TODO: Transpose the array using .transpose() method
transposed_transpose = arr.transpose()

# Print the original array and the transposed arrays
print("Original array:")
print(arr)
print("\nTransposed array using .T method:")
print(transposed_T)
print("\nTransposed array using .transpose() method:")
print(transposed_transpose)

Original array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Transposed array using .T method:
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]

Transposed array using .transpose() method:
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


### Exercise 16: Array Transposition

You have a 4-dimensional array and need to transpose it, swapping the last two dimensions or the middle two dimensions. Transpose a given 4-dimensional array of shape (2, 3, 4, 5) along the specified dimensions.

In [16]:
# TODO: Define a 4-dimensional random array of shape (2, 3, 4, 5) using np.random.randint()
arr = np.random.randint(0, 10, size=(2, 3, 4, 5))

# TODO: Transpose the array along the last two dimensions
transposed_last_two = np.transpose(arr, axes=(0, 1, 3, 2))

# TODO: Print the transposed array along the last two dimensions
print("Transposed array along the last two dimensions:")
print(transposed_last_two)

# TODO: Transpose the array along the middle two dimensions
transposed_middle_two = np.transpose(arr, axes=(0, 2, 1, 3))

# TODO: Print the transposed array along the middle two dimensions
print("\nTransposed array along the middle two dimensions:")
print(transposed_middle_two)

Transposed array along the last two dimensions:
[[[[8 8 6 8]
   [0 6 5 7]
   [7 6 9 3]
   [0 4 1 6]
   [1 2 1 4]]

  [[1 1 2 1]
   [7 9 9 5]
   [8 8 0 5]
   [2 9 9 9]
   [2 8 6 3]]

  [[7 3 3 9]
   [1 2 0 6]
   [3 6 7 9]
   [5 3 7 5]
   [4 4 2 2]]]


 [[[5 5 0 1]
   [3 1 5 5]
   [1 3 1 4]
   [4 1 0 5]
   [6 6 0 7]]

  [[0 7 6 9]
   [6 8 5 9]
   [0 6 6 2]
   [1 4 5 3]
   [5 6 7 2]]

  [[7 4 8 7]
   [2 3 0 0]
   [4 5 2 3]
   [3 7 4 1]
   [2 4 3 4]]]]

Transposed array along the middle two dimensions:
[[[[8 0 7 0 1]
   [1 7 8 2 2]
   [7 1 3 5 4]]

  [[8 6 6 4 2]
   [1 9 8 9 8]
   [3 2 6 3 4]]

  [[6 5 9 1 1]
   [2 9 0 9 6]
   [3 0 7 7 2]]

  [[8 7 3 6 4]
   [1 5 5 9 3]
   [9 6 9 5 2]]]


 [[[5 3 1 4 6]
   [0 6 0 1 5]
   [7 2 4 3 2]]

  [[5 1 3 1 6]
   [7 8 6 4 6]
   [4 3 5 7 4]]

  [[0 5 1 0 0]
   [6 5 6 5 7]
   [8 0 2 4 3]]

  [[1 5 4 5 7]
   [9 9 2 3 2]
   [7 0 3 1 4]]]]


## File I/O with NumPy

### Exercise 17: Writing to CSV

You have a NumPy array and need to save it as a CSV file. Save a given NumPy array to a CSV file.

In [17]:
# Given a NumPy array of data
data = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Given CSV file path
csv_file_path = 'data.csv'

# TODO: Save the NumPy array to a CSV file using np.savetxt()
np.savetxt(csv_file_path, data, delimiter=',')

print("CSV file saved successfully!")

CSV file saved successfully!


### Exercise 18: Reading from CSV

You have a CSV file containing a dataset and need to read it into a NumPy array. Read the contents of a given CSV file into a NumPy array.

In [18]:
# Given CSV file path
csv_file_path = 'data.csv'

# TODO: Read the CSV file into a NumPy array using np.loadtxt()
data = np.loadtxt(csv_file_path, delimiter=',')

# Print the data array
print(data)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


### Exercise 19: Loading and Saving NumPy Arrays using .npy files

You have a NumPy array and need to save it to a .npy file and then load it back into memory.

In [19]:
# Given NumPy array
data = np.array([1, 2, 3, 4, 5])

# Given .npy file path
npy_file = 'output.npy'

# TODO: Save the NumPy array to a .npy file using np.save()
np.save(npy_file, data)

# TODO: Load the .npy file back into memory using np.load()
loaded_data = np.load(npy_file)

# Print the original data and the loaded data
print("Original data:", data)
print("Loaded data:", loaded_data)

Original data: [1 2 3 4 5]
Loaded data: [1 2 3 4 5]
